default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  port: 5432
  username: <%= ENV['USER'] %>
  database: gig_manager_development

test:
  <<: *default
  host: localhost
  port: 5432
  username: <%= ENV['USER'] %>
  database: gig_manager_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>